import { React, useEffect, useState } from "react";

import Head from "next/head";
import Script from "next/script";
//import Image from 'next/image'

import Layout from "./../components/layout";
import PlantItem from "./../components/plantItem";
import BasicButton from "./../components/atoms/basicButton";

import * as CollapsiblePrimitive from "@radix-ui/react-collapsible";
export const Collapsible = CollapsiblePrimitive.Root;
export const CollapsibleTrigger = CollapsiblePrimitive.Trigger;
export const CollapsibleContent = CollapsiblePrimitive.Content;

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleRight } from "@fortawesome/free-solid-svg-icons";

const arrowIcon = (
  <FontAwesomeIcon id="arrow-right" icon={faAngleRight} className="rotate-90" />
);

//🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries
import {
  getFirestore,
  collection,
  getDocs,
  addDoc,
  deleteDoc,
  doc,
} from "firebase/firestore";

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyDKv_lZfpfFkdjtqJptVwv-talUnYrMUbo",
  authDomain: "indoor-garden-b4585.firebaseapp.com",
  projectId: "indoor-garden-b4585",
  storageBucket: "indoor-garden-b4585.appspot.com",
  messagingSenderId: "1093253453203",
  appId: "1:1093253453203:web:d34b9fe7e402b010d9c466",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Cloud Firestore and get a reference to the service
const db = getFirestore(app);

//collection ref
const colRef = collection(db, "plants");

//get collection data
getDocs(colRef)
  .then((snapshot) => {
    let plants = [];
    snapshot.docs.forEach((plant) => {
      plants.push({ ...plant.data(), id: plant.id });
    });
    console.log(plants);
  })
  .catch((err) => {
    console.log(err.message);
  });

//deleting documents

//🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

export default function Home() {
  const [open, setOpen] = useState(false);

  //🔥🔥🔥🔥🔥🔥🔥🔥⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️⬇️🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

  useEffect(() => {
    //adding firestore documents
    const addPlantForm = document.querySelector(".add");
    addPlantForm.addEventListener("submit", (e) => {
      e.preventDefault();
      addDoc(colRef, {
        commonName: addPlantForm.commonName.value,
      }).then(() => {
        addPlantForm.reset();
      });
      //console.log("add press");
    });

    //deleting firestore documents
    const deletePlantForm = document.querySelector(".delete");
    deletePlantForm.addEventListener("submit", (e) => {
      e.preventDefault();

      const docRef = doc(db, "plants", deletePlantForm.id.value);
      deleteDoc(docRef).then(() => {
        deletePlantForm.reset();
      });

      //console.log("delete press");
    });
  });
  //🔥🔥🔥🔥🔥🔥🔥🔥⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆️⬆️🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

  return (
    <Layout>
      <div>
        <Head>
          <title>Indoor Garden</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#5C8B57" />
          <link rel="apple-touch-icon" href="/images/app_icons/icon.png" />
          <meta name="apple-mobile-web-app-status-bar" content="#5C8B57" />
        </Head>

        <main className="min-h-screen">
          <section className=" mx-6">
            <PlantItem
              icon="🌸"
              name="Doris"
              popularName="Cherry Blossom"
              timeTillNextWater="2"
              wateringStreak="24"
              level="1"
            />
            <PlantItem
              icon="🌷"
              name="Saturn"
              popularName="Tulip"
              timeTillNextWater="1"
              wateringStreak="142"
              level="3"
            />
            <PlantItem
              icon="🌻"
              name="Herschel"
              popularName="Sunflower"
              timeTillNextWater="85"
              wateringStreak="5"
              level="2"
            />
            {/* <BasicButton id="more-button" bgColor="bg-water-100" innerText="Less" otherText="More" icon={arrowIcon} />         */}
            <Collapsible open={open} onOpenChange={setOpen}>
              <CollapsibleTrigger className="mb-6">
                <BasicButton bgColor="bg-water-100">
                  {open ? "Show less" : "Show more"}
                </BasicButton>
              </CollapsibleTrigger>
              <CollapsibleContent>
                <PlantItem
                  icon="🌵"
                  name="Kelper"
                  popularName="Saguaro Cactus"
                  timeTillNextWater="38"
                  wateringStreak="174"
                  level="5"
                />
                <PlantItem
                  icon="🥬"
                  name="Bain"
                  popularName="Romaine Lettuce"
                  timeTillNextWater="4"
                  wateringStreak="8"
                  level="1"
                />
              </CollapsibleContent>
            </Collapsible>
          </section>
          <section>
            <form className="add flex gap-2">
              <label for="commonName">Common Name:</label>
              <input
                type="text"
                name="commonName"
                className="text-black"
              ></input>

              <button>
                <BasicButton bgColor="bg-water-100">Add new plant</BasicButton>
              </button>
            </form>
            <br></br>
            <form className="delete flex gap-2">
              <label for="id">Common Name:</label>
              <input type="text" name="id" className="text-black"></input>

              <button>
                <BasicButton bgColor="bg-red-300">Delete plant</BasicButton>
              </button>
            </form>
          </section>
        </main>
      </div>
    </Layout>
  );
}
