import {useEffect, useState } from "react";
import * as React from "react";

import Head from "next/head";

import Layout from "../components/layout";
import PlantItem from "../components/plantItem";
import NewForm from "../components/newForm";

import { Button, ButtonGroup } from '@chakra-ui/react'

import { getPlants, getPlant, addPlant } from "../data/plants";

export default function Home() {

  const plantList: object[] = []
  const [plants, setPlants] = useState(plantList);

  return (
    <Layout>
      <div>
        <Head>
          <title>Indoor Garden</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />

          <link rel="manifest" href="/manifest.json" />
          <meta name="theme-color" content="#5C8B57" />
          <link rel="apple-touch-icon" href="/images/app_icons/icon.png" />
          <meta name="apple-mobile-web-app-status-bar" content="#5C8B57" />
        </Head>

        <main className="min-h-screen">
          <section className=" mx-6">
            {getPlants().map((plant, index) => (
              //show local storage plants
              <PlantItem
                key={index}
                icon={plant.icon}
                name={plant.nickname}
                commonName={plant.commonName}
                timeTillNextWater={plant.timeTillNextWater}
                wateringStreak={plant.wateringStreak}
                level={plant.level}
                children={undefined}
              />
            ))}
          </section>
          <NewForm setPlants={setPlants}/>
        </main>
      </div>
    </Layout>
  );
}
