# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/commands/install_yarn_deps
      - run: yarn tsc --build
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code with git
      - uses: actions/checkout@master

      # Install Yarn dependencies
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: "14.17.3"
      - run: npm install -g "yarn@1.22.5"
      - run: yarn install --immutable

      # Build command
      - run: yarn build
