name: Run Test Build

on:
  pull_request:
    types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Install Yarn dependencies
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: "14.17.3"
      - run: npm install -g "yarn@1.22.5"
      - run: yarn install --immutable

      - run: yarn tsc --build
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code with git
      - uses: actions/checkout@master

      # Install Yarn dependencies
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: "14.17.3"
      - run: npm install -g "yarn@1.22.5"
      - run: yarn install --immutable

      # Build command
      - run: yarn build
